language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode # rubinious in 1.8 mode
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
#
# From http://stackoverflow.com/questions/16924151/how-to-test-and-document-jruby-compatibility-for-a-gem-with-some-c-exts
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
